name: Update README with Docker image

on:
  push:
    branches:
      - dev

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "## Docker Image Details" >> README.md
          echo "- **Image Name**: \${{ env.IMAGE_NAME }}" >> README.md
          echo "- **Image ID**: \${{ env.IMAGE_ID }}" >> README.md
          echo "- **Image Size**: N/A" >> README.md  # Replace with actual size if available
        env:
          IMAGE_NAME: jakuzzibubbles/my-portfolio
          IMAGE_ID: 3e31d43069cb
